version: '3.9'

services:
  django:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8006
    volumes:
      - .:/code
    ports:
      - "8006:8006"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A django_celery worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env


  flower:
    build: .
    container_name: flower
    command: celery -A django_celery flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
    env_file:
      - .env